---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbird-peer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netbird-peer
  template:
    metadata:
      labels:
        app: netbird-peer
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - netbird-peer
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: netbird
          image: netbirdio/netbird:latest
          env:
            - name: NB_MANAGEMENT_URL
              value: "{{ .Values.managementUrl }}"
            - name: NB_SETUP_KEY
              valueFrom:
                secretKeyRef:
                  name: netbird-peer
                  key: setup-key
            - name: NB_HOSTNAME
              value: "{{ .Values.hostname }}"
            - name: NB_LOG_LEVEL
              value: "{{ .Values.logLevel }}"
          resources:
            requests:
              cpu: "250m"
              memory: "128Mi"
            limits:
              cpu: "1"
              memory: "512Mi"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_RESOURCE
                - SYS_ADMIN
