---
apiVersion: stackgres.io/v1
kind: SGPostgresConfig
metadata:
  name: {{ .Release.Name }}
spec:
  postgresVersion: {{ .Values.postgresVersion | quote }}
  postgresql.conf:
    shared_buffers: {{ .Values.postgresConfig.shared_buffers }}
    random_page_cost: {{ .Values.postgresConfig.random_page_cost | quote }}
    password_encryption: {{ .Values.postgresConfig.password_encryption }}
    log_checkpoints: {{ .Values.postgresConfig.log_checkpoints | quote }}
