{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "aerith.fullname" . }}-leader-election-rolebinding
  labels:
    {{- include "aerith.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "aerith.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "aerith.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
