{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aerith.fullname" . }}-solution-generator
  labels:
    {{- include "aerith.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
{{- end }}
