{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "aerith.fullname" . }}-solution-generator-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aerith.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "aerith.fullname" . }}-solution-generator-role
subjects:
- kind: ServiceAccount
  name: {{ include "aerith.fullname" . }}-solution-generator
  namespace: {{ .Release.Namespace }}
{{- end }}
