apiVersion: v2
name: aerith
description: A Helm chart for the Aerith Kubernetes operator.
type: application
version: 0.1.0
appVersion: "v0.0.1"
keywords:
  - aerith
  - operator
  - kubernetes
  - controller
  - trello
  - gemini
home: https://github.com/footprint-it-solutions/aerith
sources:
  - https://github.com/footprint-it-solutions/aerith
maintainers:
  - name: Footprint IT Solutions
    email: info@footprint-it-solutions.com
