---
apiVersion: v2
appVersion: "v0.0.1"
description: A Helm chart for the Aerith Kubernetes operator.
keywords:
  - aerith
  - operator
  - kubernetes
  - controller
  - trello
  - gemini
maintainers:
  - name: Footprint IT Solutions
    email: engineering@footprintit.net
name: aerith
sources:
  - https://github.com/footprint-it-software-development/aerith
type: application
version: 0.1.0
